(()=>{'use strict';
const API='https://angers-au-coeur-espace.angers-au-coeur-cloudflare-v2.workers.dev/api/public/contributions';
const form=document.getElementById('public-contribution-form');if(!form)return;
const message=document.getElementById('public-message'),submit=form.querySelector('[type=submit]'),contact=document.getElementById('contact-fields');let sending=false,requestId=crypto.randomUUID();
const tell=(text,success=false)=>{message.hidden=false;message.textContent=text;message.classList.toggle('success',success);message.focus();};
form.querySelectorAll('[name=contact_mode]').forEach(radio=>radio.addEventListener('change',()=>{const anonymous=form.elements.contact_mode.value==='ANONYME';contact.hidden=anonymous;contact.disabled=anonymous;if(anonymous){['prenom','nom','email'].forEach(k=>form.elements[k].value='');['accepte_contact_contribution','accepte_actualites'].forEach(k=>form.elements[k].checked=false);}}));
async function send(path,data){const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},credentials:'omit',body:JSON.stringify(data),signal:AbortSignal.timeout(20000)});let value;try{value=await response.json();}catch{throw Error('Le service est indisponible. Aucun succès d’envoi n’est confirmé.');}if(!response.ok||!value.ok)throw Error(value.error?.message||'L’envoi n’a pas abouti. Réessayez.');return value.data;}
form.addEventListener('submit',async event=>{event.preventDefault();if(sending)return;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form)),anonymous=data.contact_mode==='ANONYME';['accepte_contact_contribution','accepte_actualites','accepte_traitement'].forEach(k=>data[k]=!!form.elements[k].checked);if(anonymous){data.prenom='';data.nom='';data.email='';data.accepte_contact_contribution=false;data.accepte_actualites=false;}if(data.email&&!data.accepte_contact_contribution&&!data.accepte_actualites){tell('Choisissez une finalité pour votre email ou retirez-le.');return;}if((data.accepte_contact_contribution||data.accepte_actualites)&&!data.email){tell('Ajoutez un email pour le recontact ou les communications.');return;}const token=data['cf-turnstile-response'];delete data['cf-turnstile-response'];if(!token){tell('Attendez la vérification anti-spam. Si elle ne s’affiche pas, rechargez la page.');return;}data.turnstile_token=token;data.request_id=requestId;data.consent_version='AAC-PUBLIC-2026-10-09-v1';sending=true;submit.disabled=true;message.hidden=true;
try{const receipt=await send(API,data);form.hidden=true;tell('Votre contribution est enregistrée. Elle sera examinée et ne sera pas publiée automatiquement.',true);const box=document.getElementById('public-receipt');box.hidden=false;box.querySelector('[data-reference]').textContent=receipt.reference;box.querySelector('[data-withdrawal]').textContent=receipt.withdrawal_key;document.getElementById('withdraw-reference').value=receipt.reference;document.getElementById('withdraw-key').value=receipt.withdrawal_key;requestId=crypto.randomUUID();}catch(error){tell(error.name==='TimeoutError'?'La réponse tarde à arriver. Réessayez : la référence d’envoi évite les doublons.':error.message||'Connexion indisponible. Réessayez.');if(window.turnstile)window.turnstile.reset();}finally{sending=false;submit.disabled=false;}});
const withdrawal=document.getElementById('withdraw-form');withdrawal.addEventListener('submit',async event=>{event.preventDefault();if(!withdrawal.reportValidity())return;const button=withdrawal.querySelector('button'),result=document.getElementById('withdraw-result');button.disabled=true;try{await send(API+'/withdraw',Object.fromEntries(new FormData(withdrawal)));result.textContent='Votre demande de retrait a été exécutée.';withdrawal.reset();}catch(error){result.textContent=error.message||'Le retrait n’a pas abouti.';}finally{button.disabled=false;}});
})();
